quarkus.application.name=automotive-quarkus
quarkus.http.port=8081

# datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=automotive
quarkus.datasource.password=Jabulani2002@
quarkus.datasource.jdbc.url=jdbc:mysql://automotive-quarkus-mysql:3306/automotive_quarkus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# hibernate
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration

# openapi / swagger
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

mp.openapi.info.title=Automotive Quarkus API
mp.openapi.info.version=1.0.0
mp.openapi.info.description=Automotive Management System built with Quarkus, Flyway, MySQL, Prometheus, and Grafana

# health / metrics
quarkus.smallrye-health.root-path=/q/health
quarkus.micrometer.export.prometheus.enabled=true

# public paths
quarkus.http.auth.permission.public.paths=/q/health,/q/health/*,/q/metrics,/q/openapi,/q/swagger-ui,/q/swagger-ui/*
quarkus.http.auth.permission.public.policy=permit

# secure api
quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated


quarkus.package.jar.type=fast-jar